export enum AuthServiceMessagePattern {
  addUser = 'addUser',
  login = 'login',
  refreshTokens = 'refreshTokens',
  updateProfile = 'updateProfile',
  blockUser = 'blockUser',
  unblockUser = 'unblockUser',
  deleteUser = 'deleteUser',
  addUserMultiple = 'addUserMultiple',
  getUser = 'getUser',
  changePassword = 'changePassword',
  sendTelegramCode = 'sendTelegramCode',
  loginTelegramCode = 'loginTelegramCode',
  telegramLogin = 'telegramLogin',
  findUsers = 'findUsers',
}
