export enum UserPosition {
  TESTER = 'TESTER',
  DEVREL = 'DEVREL',
  BE_DEVELOPER = 'BE_DEVELOPER',
  FE_DEVELOPER = 'FE_DEVELOPER',
  ANALYTICS = 'ANALYTICS',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  UNASSIGNED = 'UNASSIGNED',
}
